description = "Adds an FPS limit option to the graphics settings menu"
authors = ["janw4ld"]
supported_platforms = ["android", "ios"]

[[patch_lists]]
  version = 0
  supported_game_versions = ["1.0.1o-FULL", "1.0.1n-FULL"]
  [[patch_lists.patch_files]]
    target_file = "functions/UI_definitions.lua"
    [[patch_lists.patch_files.patches]]
      search_string = "G.UIDEF = {}"
      patch_content = """
G.UIDEF = {}
local _, _, __balatromobile_fps_cap_p_wflags = love.window.getMode()
local __balatromobile_fps_cap_options = {
  labels = {"Monitor", 30, 60, 90, 120, 144, 240, "Max"},
  reverse_lookup  = {
    ["Monitor"] = 1,
    [30] = 2,
    [60] = 3,
    [90] = 4,
    [120] = 5,
    [144] = 6,
    [240] = 7,
    ["Max"] = 8,
  },
  values  = {
    ["Monitor"] = __balatromobile_fps_cap_p_wflags.refreshrate,
    [30] = 30,
    [60] = 60,
    [90] = 90,
    [120] = 120,
    [144] = 144,
    [240] = 240,
    ["Max"] = 500,
  },
}
G.FUNCS.__balatromobile_fps_cap_callback = function(option)
  G.SETTINGS.__balatromobile_FPS_CAP = option.to_val
  G.FPS_CAP = __balatromobile_fps_cap_options.values[option.to_val]
end
G.FPS_CAP = G.FUNCS.__balatromobile_fps_cap_callback {
  to_val = G.SETTINGS.__balatromobile_FPS_CAP or "Monitor"
}
"""
    [[patch_lists.patch_files.patches]]
      search_string = "create_option_cycle({w = 4,scale = 0.8, label = localize(\"b_set_CRT_bloom\"),options = localize('ml_bloom_opt'), opt_callback = 'change_crt_bloom', current_option = G.SETTINGS.GRAPHICS.bloom}),"
      patch_content = """
      create_option_cycle({w = 4,scale = 0.8, label = localize("b_set_CRT_bloom"),options = localize('ml_bloom_opt'), opt_callback = 'change_crt_bloom', current_option = G.SETTINGS.GRAPHICS.bloom}),
      {n = G.UIT.R, config = {align = "cm", r = 0}, nodes = {create_option_cycle{
        label = "FPS Limit",
        w = 4,
        scale = 0.8,
        options = __balatromobile_fps_cap_options.labels,
        opt_callback = '__balatromobile_fps_cap_callback',
        current_option =
         __balatromobile_fps_cap_options.reverse_lookup[G.SETTINGS.__balatromobile_FPS_CAP],
      }}},
"""
